services:
  postgres:
    image: postgres:16
    container_name: minihittegods-postgres
    environment:
      POSTGRES_DB: minihittegods
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - minihittegods_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: MiniHittegods.Api/Dockerfile
    container_name: minihittegods-api
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=minihittegods;Username=postgres;Password=postgres"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgres #Todo: legge til health-check, spør ai

volumes:
  minihittegods_data: